# Generated by Django 6.0.3 on 2026-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_created_show_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
