# Generated by Django 6.0.3 on 2026-04-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0003_showmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowManager',
        ),
    ]
