# Generated by Django 6.0.3 on 2026-05-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0005_rename_annotations_play_annotation_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='annotation',
            new_name='annotations',
        ),
    ]
